### ISSUE TITLE
Sleep and Wake

### ISSUE THREAD

**Issue by MrZarmani** [hackintosh-efi/DELL-3090MFF-OpenCore#2]
Do sleep and wake work on your  DELL 3090MFF?
Mine goes restart upon every wake attempt. 
(Failure during sleep: 0xFFFFFFFF 0000001F : EFI/Bootrom Failure after last point of entry to sleep)

Any idea what the problem is?

**Comment by WuLongMiTaoLaiYiDa** [comment]
1.check bios setup ，2.did u rebuild usbport kext ？
it's work fine on my 3090
